
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `EasyML`=list(
        `type`="software", 
        `author`="Mart\u00EDnez-Garc\u00EDa, J., Monta\u00F1o, J. J., & Ses\u00E9, A.", 
        `year`=2025, 
        `title`="EasyML: Machine Learning for Everyone", 
        `publisher`="(Version 7.5.6) [jamovi module]. URL https://github.com/JMartinezGarcia/MLwrap", 
        `url`="https://github.com/JMartinezGarcia/MLwrap"), 
    `MLwrap`=list(
        `type`="software", 
        `author`="Mart\u00EDnez-Garc\u00EDa, J., Monta\u00F1o, J. J., & Ses\u00E9, A.", 
        `year`=2025, 
        `title`="MLwrap: Machine Learning Modelling for Everyone", 
        `publisher`="(Version 0.2.1) [R package]. URL https://CRAN.R-project.org/package=MLwrap", 
        `url`="https://CRAN.R-project.org/package=MLwrap"))
